<?php

namespace Database\Seeders;

use App\Models\Exercise;
use App\Models\MuscleGroup;
use Illuminate\Database\Seeder;

class ExerciseSeeder extends Seeder
{
    public function run(): void
    {
        $byName = MuscleGroup::pluck('id', 'name');

        $exercises = [
            'Chest' => [
                ['name' => 'Incline Barbell Bench Press', 'difficulty' => 'intermediate', 'equipment' => 'Barbell, Incline Bench',
                    'description' => 'Compound press targeting the upper chest (clavicular head).',
                    'instructions' => "1. Set bench to 30-45°.\n2. Grip bar slightly wider than shoulders.\n3. Lower to upper chest.\n4. Press up explosively.",
                    'image' => 'images/exercises/incline-barbell-bench-press.jpg'],
                ['name' => 'Incline Dumbbell Press', 'difficulty' => 'intermediate', 'equipment' => 'Dumbbells, Incline Bench',
                    'description' => 'Dumbbell variation for upper chest with greater range of motion.',
                    'instructions' => "1. Set bench to 30-45°.\n2. Hold dumbbells at chest level.\n3. Press up and together.\n4. Lower with control.",
                    'image' => 'images/exercises/incline-dumbbell-press.jpg'],
                ['name' => 'Incline Chest Press Machine', 'difficulty' => 'beginner', 'equipment' => 'Chest Press Machine',
                    'description' => 'Machine-based upper chest press, great for beginners.',
                    'instructions' => "1. Adjust seat so handles align with upper chest.\n2. Press forward until arms are extended.\n3. Return slowly.",
                    'image' => 'images/exercises/machine-incline-chest-press.jpg'],
                ['name' => 'Feet Elevated Push-ups', 'difficulty' => 'beginner', 'equipment' => 'None',
                    'description' => 'Bodyweight push-up variation that shifts focus to the upper chest.',
                    'instructions' => "1. Place feet on a bench or box.\n2. Hands on the floor shoulder-width.\n3. Lower chest to floor.\n4. Push back up.",
                    'image' => 'images/exercises/feet-elevated-push-up.jpg'],
                ['name' => 'Incline Dumbbell Fly', 'difficulty' => 'beginner', 'equipment' => 'Dumbbells, Incline Bench',
                    'description' => 'Isolation movement stretching the upper chest fibres.',
                    'instructions' => "1. Lie on incline bench.\n2. Hold dumbbells above chest, slight elbow bend.\n3. Open arms wide in an arc.\n4. Squeeze chest to return.",
                    'image' => 'images/exercises/incline-dumbbell-fly.jpg'],
                ['name' => 'Low-to-High Cable Fly', 'difficulty' => 'beginner', 'equipment' => 'Cable Machine',
                    'description' => 'Cable fly with upward arc to target upper chest.',
                    'instructions' => "1. Set cables at lowest position.\n2. Stand in middle, grab handles.\n3. Pull up and together in an arc.\n4. Squeeze at the top.",
                    'image' => 'images/exercises/low-to-high-cable-fly.jpg'],
                ['name' => 'Incline Cable Fly', 'difficulty' => 'intermediate', 'equipment' => 'Cable Machine, Incline Bench',
                    'description' => 'Cable fly on incline bench for constant tension on upper chest.',
                    'instructions' => "1. Set cables low, lie on incline bench between them.\n2. Pull handles up and together.\n3. Hold squeeze, return slowly.",
                    'image' => 'images/exercises/incline-cable-fly.jpg'],
                ['name' => 'Incline Pec Deck', 'difficulty' => 'beginner', 'equipment' => 'Pec Deck Machine',
                    'description' => 'Machine fly variation isolating the upper chest.',
                    'instructions' => "1. Adjust machine arms to upper chest height.\n2. Sit upright.\n3. Bring arms together squeezing chest.\n4. Return slowly.",
                    'image' => 'images/exercises/pec-deck-fly.jpg'],

                ['name' => 'Flat Bench Press', 'difficulty' => 'intermediate', 'equipment' => 'Barbell, Bench',
                    'description' => 'Classic compound press for overall chest mass.',
                    'instructions' => "1. Lie flat on bench.\n2. Grip bar slightly wider than shoulders.\n3. Lower to mid-chest.\n4. Press up powerfully.",
                    'image' => 'images/exercises/barbell-bench-press.jpg'],
                ['name' => 'Dumbbell Bench Press', 'difficulty' => 'intermediate', 'equipment' => 'Dumbbells, Bench',
                    'description' => 'Flat dumbbell press for chest with greater range of motion.',
                    'instructions' => "1. Lie flat, dumbbells at chest.\n2. Press up and slightly together.\n3. Lower to chest level.\n4. Repeat.",
                    'image' => 'images/exercises/dumbbell-bench-press.jpg'],
                ['name' => 'Push-Up', 'difficulty' => 'beginner', 'equipment' => 'None',
                    'description' => 'Bodyweight staple for chest and triceps.',
                    'instructions' => "1. Hands shoulder-width on floor.\n2. Lower body until chest nearly touches floor.\n3. Push back up fully.",
                    'image' => 'images/exercises/push-up.jpg'],
                ['name' => 'Chest Press Machine', 'difficulty' => 'beginner', 'equipment' => 'Chest Press Machine',
                    'description' => 'Guided machine press for the mid chest.',
                    'instructions' => "1. Align handles with mid chest.\n2. Press forward until arms extended.\n3. Return under control.",
                    'image' => 'images/exercises/machine-chest-press.jpg'],
                ['name' => 'Dumbbell Fly (Flat)', 'difficulty' => 'beginner', 'equipment' => 'Dumbbells, Bench',
                    'description' => 'Flat bench fly for mid chest isolation.',
                    'instructions' => "1. Lie flat, dumbbells above chest.\n2. Open arms wide with soft elbows.\n3. Squeeze chest to bring them back.",
                    'image' => 'images/exercises/dumbbell-fly.jpg'],
                ['name' => 'Cable Fly (Mid Level)', 'difficulty' => 'beginner', 'equipment' => 'Cable Machine',
                    'description' => 'Mid-level cable fly for constant tension on chest.',
                    'instructions' => "1. Set cables to chest height.\n2. Stand in middle, lean slightly forward.\n3. Pull handles together in arc.\n4. Squeeze and return.",
                    'image' => 'images/exercises/cable-chest-fly.jpg',],
                ['name' => 'Pec Deck Fly', 'difficulty' => 'beginner', 'equipment' => 'Pec Deck Machine',
                    'description' => 'Machine fly for mid chest isolation.',
                    'instructions' => "1. Sit with back flat, arms on pads.\n2. Bring pads together squeezing chest.\n3. Return slowly with control.",
                    'image' => 'images/exercises/pec-deck-fly.jpg'],
                ['name' => 'Cable Crossover', 'difficulty' => 'intermediate', 'equipment' => 'Cable Machine',
                    'description' => 'Classic cable crossover for chest definition.',
                    'instructions' => "1. Set cables high.\n2. Step forward, pull handles down and together.\n3. Cross hands at bottom.\n4. Return slowly.",
                    'image' => 'images/exercises/cable-crossover.jpg'],

                ['name' => 'Decline Bench Press', 'difficulty' => 'intermediate', 'equipment' => 'Barbell, Decline Bench',
                    'description' => 'Compound press targeting the lower chest.',
                    'instructions' => "1. Set bench to decline (-15 to -30°).\n2. Grip bar wider than shoulders.\n3. Lower to lower chest.\n4. Press up.",
                    'image' => 'images/exercises/decline-barbell-bench-press.jpg'],
                ['name' => 'Decline Dumbbell Press', 'difficulty' => 'intermediate', 'equipment' => 'Dumbbells, Decline Bench',
                    'description' => 'Dumbbell decline press for lower chest.',
                    'instructions' => "1. Lie on decline bench.\n2. Press dumbbells up from lower chest.\n3. Lower under control.",
                    'image' => 'images/exercises/decline-dumbbell-press.jpg'],
                ['name' => 'Chest Dips', 'difficulty' => 'intermediate', 'equipment' => 'Dip Bars',
                    'description' => 'Bodyweight dip leaning forward to target lower chest.',
                    'instructions' => "1. Grip dip bars, lean torso forward.\n2. Lower body bending elbows.\n3. Press back up squeezing chest.",
                    'image' => 'images/exercises/chest-dip.jpg'],
                ['name' => 'Decline Push-ups', 'difficulty' => 'beginner', 'equipment' => 'None',
                    'description' => 'Feet-elevated push-up targeting lower chest.',
                    'instructions' => "1. Place hands on floor, feet on bench.\n2. Lower chest to floor.\n3. Push back up.",
                    'image' => 'images/exercises/decline-push-up.jpg'],
                ['name' => 'High-to-Low Cable Fly', 'difficulty' => 'beginner', 'equipment' => 'Cable Machine',
                    'description' => 'Cable fly with downward arc targeting lower chest.',
                    'instructions' => "1. Set cables high.\n2. Pull handles down and together in an arc.\n3. Squeeze at the bottom.",
                    'image' => 'images/exercises/high-to-low-cable-fly.jpg'],
                ['name' => 'Decline Cable Fly', 'difficulty' => 'intermediate', 'equipment' => 'Cable Machine, Decline Bench',
                    'description' => 'Cable fly on decline bench for lower chest isolation.',
                    'instructions' => "1. Set cables high, lie on decline bench.\n2. Pull handles down and together.\n3. Return slowly.",
                    'image' => 'images/exercises/decline-cable-fly.jpg'],
                ['name' => 'Low Cable Crossover', 'difficulty' => 'intermediate', 'equipment' => 'Cable Machine',
                    'description' => 'Crossover variation targeting lower chest fibres.',
                    'instructions' => "1. Set cables to lowest position.\n2. Pull handles up and together crossing at chest height.\n3. Return with control.",
                    'image' => 'images/exercises/cable-crossover.jpg'],
            ],

            'Back' => [
                // ── LATS (Width) ── Compound
                ['name' => 'Pull-ups (Wide Grip)', 'difficulty' => 'intermediate', 'equipment' => 'Pull-up Bar',
                    'description' => 'Wide-grip pull-up targeting lat width and V-taper.',
                    'instructions' => "1. Grip bar wider than shoulders, palms facing away.\n2. Hang fully, then pull chest toward bar.\n3. Squeeze lats at top.\n4. Lower with control.",
                    'image' => 'images/exercises/pull-up.jpg'],
                ['name' => 'Lat Pulldown', 'difficulty' => 'beginner', 'equipment' => 'Cable Machine',
                    'description' => 'Cable alternative to pull-ups for lat width.',
                    'instructions' => "1. Sit and grip bar wider than shoulders.\n2. Pull bar to upper chest.\n3. Squeeze lats at bottom.\n4. Control the return.",
                    'image' => 'images/exercises/lat-pulldown.jpg'],
                ['name' => 'Chin-ups', 'difficulty' => 'intermediate', 'equipment' => 'Pull-up Bar',
                    'description' => 'Underhand pull-up hitting lats and biceps.',
                    'instructions' => "1. Grip bar shoulder-width, palms facing you.\n2. Pull chin above bar.\n3. Lower slowly.",
                    'image' => 'images/exercises/chin-up.jpg'],
                ['name' => 'Straight Arm Pulldown', 'difficulty' => 'beginner', 'equipment' => 'Cable Machine',
                    'description' => 'Isolation movement for lat activation with arms straight.',
                    'instructions' => "1. Stand at cable, arms straight, grip bar overhead.\n2. Pull bar down to hips keeping arms straight.\n3. Squeeze lats at bottom.\n4. Return slowly.",
                    'image' => 'images/exercises/straight-arm-pulldown.jpg'],
                // ── LATS ── Isolation
                ['name' => 'Single-Arm Lat Pulldown', 'difficulty' => 'beginner', 'equipment' => 'Cable Machine',
                    'description' => 'Unilateral lat pulldown for balanced development.',
                    'instructions' => "1. Attach single handle to cable.\n2. Sit and pull one arm at a time to shoulder.\n3. Squeeze lat at bottom.\n4. Return and repeat.",
                    'image' => 'images/exercises/single-arm-lat-pulldown.jpg'],
                ['name' => 'Kneeling Cable Pulldown', 'difficulty' => 'beginner', 'equipment' => 'Cable Machine',
                    'description' => 'Kneeling variation for stretch-focused lat isolation.',
                    'instructions' => "1. Kneel facing cable machine.\n2. Grip bar overhead.\n3. Pull elbows to sides squeezing lats.\n4. Return with control.",
                    'image' => 'images/exercises/lat-pulldown.jpg'],

                // ── UPPER BACK (Thickness) ── Compound
                ['name' => 'Barbell Bent-over Row', 'difficulty' => 'intermediate', 'equipment' => 'Barbell',
                    'description' => 'King of upper back thickness — hits traps, rhomboids and lats.',
                    'instructions' => "1. Hinge at hips, back flat, bar hanging.\n2. Pull bar to lower chest.\n3. Squeeze shoulder blades together.\n4. Lower with control.",
                    'image' => 'images/exercises/barbell-bent-over-row.jpg'],
                ['name' => 'T-Bar Row', 'difficulty' => 'intermediate', 'equipment' => 'T-Bar Machine / Barbell',
                    'description' => 'Compound row for mid-back thickness.',
                    'instructions' => "1. Straddle bar, hinge forward.\n2. Grip handles and row to chest.\n3. Squeeze mid-back.\n4. Lower slowly.",
                    'image' => 'images/exercises/t-bar-row.jpg'],
                ['name' => 'Seated Cable Row', 'difficulty' => 'beginner', 'equipment' => 'Cable Machine',
                    'description' => 'Horizontal cable row for upper back thickness.',
                    'instructions' => "1. Sit upright, feet on platform.\n2. Pull handle to lower chest.\n3. Elbows close to body.\n4. Return slowly.",
                    'image' => 'images/exercises/seated-cable-row.jpg'],
                ['name' => 'Dumbbell Row', 'difficulty' => 'beginner', 'equipment' => 'Dumbbell, Bench',
                    'description' => 'Unilateral row for upper back and lats.',
                    'instructions' => "1. Plant one knee and hand on bench.\n2. Row dumbbell to hip.\n3. Squeeze lat at top.\n4. Lower with control.",
                    'image' => 'images/exercises/single-arm-dumbbell-row.jpg'],
                // ── UPPER BACK ── Isolation
                ['name' => 'Face Pull', 'difficulty' => 'beginner', 'equipment' => 'Cable Machine, Rope',
                    'description' => 'Rear delt and upper trap isolation.',
                    'instructions' => "1. Set cable to upper chest height.\n2. Pull rope to face, elbows flared high.\n3. Squeeze rear delts.\n4. Return slowly.",
                    'image' => 'images/exercises/face-pull.jpg'],
                ['name' => 'Reverse Pec Deck', 'difficulty' => 'beginner', 'equipment' => 'Pec Deck Machine',
                    'description' => 'Machine isolation for rear delts and rhomboids.',
                    'instructions' => "1. Sit facing pad, grip handles.\n2. Pull arms back squeezing rear delts.\n3. Hold briefly.\n4. Return slowly.",
                    'image' => 'images/exercises/reverse-pec-deck.jpg'],
                ['name' => 'Cable Rear Delt Row', 'difficulty' => 'beginner', 'equipment' => 'Cable Machine',
                    'description' => 'Cable row targeting rear delts and upper back.',
                    'instructions' => "1. Set cable at face height.\n2. Pull handle to ear level, elbow high.\n3. Squeeze rear delt.\n4. Return slowly.",
                    'image' => 'images/exercises/face-pull.jpg'],
                ['name' => 'Machine High Row', 'difficulty' => 'beginner', 'equipment' => 'High Row Machine',
                    'description' => 'Machine row from a high angle targeting upper back.',
                    'instructions' => "1. Sit and grip handles above head.\n2. Pull down and back to chest.\n3. Squeeze shoulder blades.\n4. Return slowly.",
                    'image' => 'images/exercises/lat-pulldown.jpg'],

                // ── LOWER BACK (Erector Spinae) ── Compound
                ['name' => 'Deadlift', 'difficulty' => 'advanced', 'equipment' => 'Barbell',
                    'description' => 'Full-body compound lift — king of lower back and posterior chain.',
                    'instructions' => "1. Stand over bar, feet hip-width.\n2. Hinge and grip bar just outside knees.\n3. Drive through floor, keeping back neutral.\n4. Lock out hips at top.\n5. Lower with control.",
                    'image' => 'images/exercises/barbell-deadlift.jpg'],
                ['name' => 'Romanian Deadlift', 'difficulty' => 'intermediate', 'equipment' => 'Barbell',
                    'description' => 'Hip-hinge movement targeting lower back and hamstrings.',
                    'instructions' => "1. Start standing, soft knees.\n2. Hinge at hips lowering bar along legs.\n3. Feel hamstring stretch.\n4. Drive hips forward to stand.",
                    'image' => 'images/exercises/romanian-deadlift.jpg'],
                ['name' => 'Rack Pull', 'difficulty' => 'intermediate', 'equipment' => 'Barbell, Rack',
                    'description' => 'Partial deadlift from knee height for lower back overload.',
                    'instructions' => "1. Set bar at knee height in rack.\n2. Grip bar and stand upright.\n3. Lower back to rack.\n4. Keep back tight throughout.",
                    'image' => 'images/exercises/rack-pull.jpg'],
                ['name' => 'Good Morning', 'difficulty' => 'intermediate', 'equipment' => 'Barbell',
                    'description' => 'Barbell hip hinge for erector spinae strength.',
                    'instructions' => "1. Bar on upper traps.\n2. Hinge forward at hips, back flat.\n3. Lower until parallel to floor.\n4. Drive hips to stand.",
                    'image' => 'images/exercises/good-morning.jpg'],
                // ── LOWER BACK ── Isolation
                ['name' => 'Back Extension', 'difficulty' => 'beginner', 'equipment' => 'Hyperextension Bench',
                    'description' => 'Isolation for erector spinae on the hyperextension bench.',
                    'instructions' => "1. Lock feet in bench, hips at pad edge.\n2. Lower torso toward floor.\n3. Raise back to parallel.\n4. Squeeze lower back at top.",
                    'image' => 'images/exercises/back-extension.jpg'],
                ['name' => 'Reverse Hyperextension', 'difficulty' => 'beginner', 'equipment' => 'Hyperextension Bench',
                    'description' => 'Reverse movement decompressing spine and strengthening glutes and lower back.',
                    'instructions' => "1. Lie face down on bench, legs hanging.\n2. Raise legs until parallel to floor.\n3. Squeeze glutes and lower back.\n4. Lower slowly.",
                    'image' => 'images/exercises/reverse-hyperextension.jpg'],
                ['name' => 'Superman Hold', 'difficulty' => 'beginner', 'equipment' => 'None',
                    'description' => 'Bodyweight lower back and glute activation.',
                    'instructions' => "1. Lie face down on floor.\n2. Raise arms and legs off floor simultaneously.\n3. Hold for 2-3 seconds.\n4. Lower and repeat.",
                    'image' => 'images/exercises/superman.jpg'],

                // ── TERES (Detail / Outer Back) ── Compound
                ['name' => 'Neutral Grip Pull-ups', 'difficulty' => 'intermediate', 'equipment' => 'Pull-up Bar',
                    'description' => 'Neutral grip pull-up hitting teres major and lats.',
                    'instructions' => "1. Grip parallel handles, palms facing each other.\n2. Pull chest to bar.\n3. Squeeze outer back.\n4. Lower slowly.",
                    'image' => 'images/exercises/pull-up.jpg'],
                ['name' => 'Close Grip Lat Pulldown', 'difficulty' => 'beginner', 'equipment' => 'Cable Machine',
                    'description' => 'Close grip variation shifting focus to teres and inner lats.',
                    'instructions' => "1. Use close/neutral grip attachment.\n2. Pull to upper chest.\n3. Squeeze lower lats and teres.\n4. Return slowly.",
                    'image' => 'images/exercises/lat-pulldown.jpg'],
                ['name' => 'Underhand Pulldown', 'difficulty' => 'beginner', 'equipment' => 'Cable Machine',
                    'description' => 'Supinated grip pulldown for teres and bicep involvement.',
                    'instructions' => "1. Grip bar with palms facing you.\n2. Pull bar to upper chest.\n3. Squeeze lats and teres.\n4. Return slowly.",
                    'image' => 'images/exercises/lat-pulldown.jpg'],
                // ── TERES ── Isolation
                ['name' => 'Cable Pull-around', 'difficulty' => 'beginner', 'equipment' => 'Cable Machine',
                    'description' => 'Single-arm cable movement isolating teres and outer lat.',
                    'instructions' => "1. Stand sideways to cable, low pulley.\n2. Pull handle across body in arc.\n3. Squeeze outer lat.\n4. Return slowly.",
                    'image' => 'images/exercises/straight-arm-pulldown.jpg'],
                ['name' => 'Stretch-focused Lat Pulldown', 'difficulty' => 'beginner', 'equipment' => 'Cable Machine',
                    'description' => 'Slow eccentric lat pulldown emphasising stretch at the top.',
                    'instructions' => "1. Use lighter weight.\n2. Pull bar to chest.\n3. Slowly return, stretching lats fully overhead.\n4. Hold stretch for 1 second.",
                    'image' => 'images/exercises/lat-pulldown.jpg'],
                ['name' => 'Single-arm Cable Row', 'difficulty' => 'beginner', 'equipment' => 'Cable Machine',
                    'description' => 'Unilateral cable row for outer back and teres detail.',
                    'instructions' => "1. Attach single handle, sit or stand.\n2. Row one arm at a time to hip.\n3. Rotate torso slightly for stretch.\n4. Return slowly.",
                    'image' => 'images/exercises/seated-cable-row.jpg'],
            ],

            'Legs' => [
                ['name' => 'Barbell Back Squat', 'difficulty' => 'advanced', 'equipment' => 'Barbell, Rack',
                    'description' => 'King of leg exercises.',
                    'instructions' => "1. Bar on upper traps.\n2. Squat to parallel or below.\n3. Drive through heels to stand.",
                    'image' => 'images/exercises/barbell-back-squat.jpg'],
                ['name' => 'Romanian Deadlift', 'difficulty' => 'intermediate', 'equipment' => 'Barbell',
                    'description' => 'Hamstring and glute focused.',
                    'instructions' => "1. Start standing, soft knees.\n2. Hinge at hips lowering bar.\n3. Feel hamstring stretch, then stand.",
                    'image' => 'images/exercises/romanian-deadlift.jpg'],
                ['name' => 'Leg Press', 'difficulty' => 'beginner', 'equipment' => 'Leg press machine',
                    'description' => 'Machine-based quad and glute builder.',
                    'instructions' => "1. Sit and place feet on platform.\n2. Release safeties.\n3. Press out, then bend knees to return.",
                    'image' => 'images/exercises/leg-press.jpg'],
            ],

            'Shoulders' => [
                ['name' => 'Overhead Press', 'difficulty' => 'intermediate', 'equipment' => 'Barbell',
                    'description' => 'Standing press for shoulder strength.',
                    'instructions' => "1. Bar at clavicle.\n2. Press overhead, locking arms.\n3. Lower to chest.",
                    'image' => 'images/exercises/barbell-overhead-press.jpg'],
                ['name' => 'Lateral Raise', 'difficulty' => 'beginner', 'equipment' => 'Dumbbells',
                    'description' => 'Isolation for side delts.',
                    'instructions' => "1. Hold dumbbells at sides.\n2. Raise arms out to shoulder level.\n3. Lower slowly.",
                    'image' => 'images/exercises/dumbbell-lateral-raise.jpg'],
                ['name' => 'Face Pull', 'difficulty' => 'beginner', 'equipment' => 'Cable, Rope',
                    'description' => 'Rear delt and upper back.',
                    'instructions' => "1. Set cable to upper chest.\n2. Pull rope to face, elbows high.\n3. Squeeze rear delts.",
                    'image' => 'images/exercises/face-pull.jpg'],
            ],

            'Arms' => [
                ['name' => 'Barbell Curl', 'difficulty' => 'beginner', 'equipment' => 'Barbell',
                    'description' => 'Classic biceps builder.',
                    'instructions' => "1. Stand with bar, palms up.\n2. Curl to shoulders.\n3. Lower under control.",
                    'image' => 'images/exercises/barbell-curl.jpg'],
                ['name' => 'Tricep Dip', 'difficulty' => 'intermediate', 'equipment' => 'Dip bars',
                    'description' => 'Bodyweight tricep movement.',
                    'instructions' => "1. Support yourself on bars.\n2. Lower body by bending elbows.\n3. Press back up.",
                    'image' => 'images/exercises/tricep-dip.jpg'],
                ['name' => 'Hammer Curl', 'difficulty' => 'beginner', 'equipment' => 'Dumbbells',
                    'description' => 'Targets biceps and forearms.',
                    'instructions' => "1. Hold dumbbells at sides, neutral grip.\n2. Curl up keeping palms facing in.\n3. Lower slowly.",
                    'image' => 'images/exercises/hammer-curl.jpg'],
            ],

            'Core' => [
                ['name' => 'Plank', 'difficulty' => 'beginner', 'equipment' => 'None',
                    'description' => 'Core stability hold.',
                    'instructions' => "1. Forearms on floor, body straight.\n2. Hold position without sagging hips.\n3. Breathe steadily.",
                    'image' => 'images/exercises/plank.jpg'],
                ['name' => 'Hanging Leg Raise', 'difficulty' => 'advanced', 'equipment' => 'Pull-up bar',
                    'description' => 'Advanced lower ab exercise.',
                    'instructions' => "1. Hang from bar.\n2. Raise legs to parallel or higher.\n3. Lower with control.",
                    'image' => 'images/exercises/hanging-leg-raise.jpg'],
                ['name' => 'Cable Crunch', 'difficulty' => 'intermediate', 'equipment' => 'Cable machine',
                    'description' => 'Weighted ab crunch.',
                    'instructions' => "1. Kneel below cable, rope overhead.\n2. Crunch down bringing elbows to knees.\n3. Return with control.",
                    'image' => 'images/exercises/cable-crunch.jpg'],
            ],
        ];

        foreach ($exercises as $muscle => $items) {
            $muscleId = $byName[$muscle] ?? null;
            if (! $muscleId) continue;
            foreach ($items as $item) {
                $item['slug'] = \Illuminate\Support\Str::slug($item['name']);
                Exercise::updateOrCreate(
                    ['name' => $item['name']],
                    array_merge($item, ['muscle_group_id' => $muscleId])
                );
            }
        }
    }
}